-- v2.1 item 4 (ROADMAP-v2 §9): fill the Question Bank's thin pools for the
-- job hunt. All rows are Prep-only (url null — answered in the app, with
-- answer_hints as the key points / requirements and AI interviewer feedback)
-- and the Coding module only selects questions that have a url.
-- Safe to re-run: each insert skips titles already in that category.
-- No backticks and no semicolons inside text: the Supabase SQL Editor's
-- statement splitter mis-split an earlier version of this file on them.

-- New 'behavioral' category, 25 general/fit questions incl. layoff, salary and closing questions (STAR competency stories stay in the Story Bank). Practice order = list order, must-haves first.
insert into coding_questions (title, difficulty, topics, sort_order, answer_hints, category, source, url)
select v.title, v.difficulty, v.topics, v.sort_order::int, v.answer_hints, 'behavioral', 'Prep additions', null
from (values
  ('Tell me about yourself.', 'easy', array['Must-have', 'Opener']::text[], 1, '90 seconds: present (role, scope, stack) → 1–2 proudest outcomes with numbers → what you''re looking for and why this role fits · end on the role, not your childhood'),
  ('Why are you looking for a new role right now?', 'easy', array['Must-have', 'Layoff']::text[], 2, 'one factual sentence about the layoff (company-wide/role eliminated, not performance), no blame or bitterness, pivot fast to what you want next and why this company'),
  ('You were laid off — what happened?', 'medium', array['Must-have', 'Layoff']::text[], 3, 'short and calm: business decision, scale if public (e.g. X% of company), what you delivered before it, what you took from it · don''t over-explain or apologize'),
  ('What have you been doing since your last role?', 'easy', array['Layoff']::text[], 4, 'structured prep (system design, AI-native workflow), a real project you built/shipped (e.g. your Personal OS app — Next.js, Supabase, AI gateway with budgets), staying sharp, being selective'),
  ('Walk me through your resume.', 'easy', array['Opener']::text[], 5, 'reverse-chronological highlights only, the thread connecting moves (growing scope toward lead), one impact per role, under 2 minutes'),
  ('Why this company?', 'medium', array['Must-have', 'Company']::text[], 6, 'specific product/engineering reason (their AI-native bar, product you''ve used, scale), link to your experience, avoid generic ''great culture'''),
  ('Why this role?', 'easy', array['Company']::text[], 7, 'match JD responsibilities to things you''ve done, the growth you want (senior/lead scope), what you''d contribute in the first 90 days'),
  ('What are you looking for in your next role?', 'easy', array['Fit']::text[], 8, 'scope (owning frontend architecture, mentoring), product impact, AI-native team, strong engineering culture · consistent with why you''re applying here'),
  ('Why should we hire you?', 'medium', array['Must-have', 'Fit']::text[], 9, '3 crisp reasons mapped to the JD: depth (React/TS/perf), leadership (raised a team''s bar), AI-native judgment · each backed by a one-line proof'),
  ('What''s your biggest strength?', 'easy', array['Fit']::text[], 10, 'one strength relevant to the role, a concrete example with outcome, not a list of adjectives'),
  ('What''s your biggest weakness?', 'medium', array['Fit']::text[], 11, 'a real but non-fatal weakness, how it showed up, the specific system you use to manage it, evidence it''s improving · never ''perfectionism'''),
  ('What are your salary expectations?', 'medium', array['Must-have', 'Logistics']::text[], 12, 'researched market range for the level and location, give a range anchored slightly high or ask for their band first, total comp not just base, flexible for the right role'),
  ('When can you start?', 'easy', array['Logistics']::text[], 13, 'available immediately / short notice — state it as a plus · mention any planned constraints honestly'),
  ('Where are you in your interview process with other companies?', 'medium', array['Logistics']::text[], 14, 'honest without oversharing, signals momentum (other loops in progress), restate genuine interest here, ask about their timeline'),
  ('Where do you see yourself in 3–5 years?', 'easy', array['Fit']::text[], 15, 'growing toward staff/lead: owning architecture and multiplying a team · ties to opportunities in this role · ambitious but grounded'),
  ('What''s the most complex frontend you''ve built?', 'hard', array['Technical depth']::text[], 16, 'context and scale, the hard parts (state, performance, real-time, a11y), your design decisions and trade-offs, measurable result, what you''d do differently'),
  ('What project are you most proud of, and why?', 'medium', array['Technical depth']::text[], 17, 'your specific role, the difficulty, impact with numbers, why it matters to you — shows values'),
  ('What does a senior or lead frontend engineer do differently from a mid-level one?', 'medium', array['Leadership']::text[], 18, 'owns ambiguity and outcomes not tickets, makes architecture/trade-off calls, raises the team''s bar (reviews, standards, mentoring), influences cross-team, thinks in years of maintenance'),
  ('How do you stay current with frontend and AI developments?', 'easy', array['Fit']::text[], 19, 'specific sources and habits, how you evaluate hype vs value, something recent you adopted or rejected and why'),
  ('How do you prioritize when everything is urgent?', 'medium', array['Fit']::text[], 20, 'clarify impact and deadlines with stakeholders, explicit trade-offs, communicate what slips, protect focus · a real example'),
  ('How do you handle feedback you disagree with?', 'medium', array['Fit']::text[], 21, 'listen first, ask for specifics, separate ego from work, test it, disagree with data and commit · example'),
  ('What would your last manager say about you?', 'easy', array['Fit']::text[], 22, '2–3 traits your manager actually praised (from reviews), one growth area they''d mention, consistent with references'),
  ('Describe your ideal team and manager.', 'easy', array['Fit']::text[], 23, 'high ownership, candid feedback, clear goals, autonomy with support — framed so it fits this company'),
  ('Do you prefer working on product features or platform/infrastructure work?', 'easy', array['Fit']::text[], 24, 'honest preference with reasoning, show you value both, connect to the role''s mix'),
  ('What questions do you have for us?', 'easy', array['Must-have', 'Closing']::text[], 25, 'always have 3–5: how AI is used in their engineering day to day, what success looks like in 90 days, biggest frontend challenge now, team structure, how decisions get made')
) as v(title, difficulty, topics, sort_order, answer_hints)
where not exists (select 1 from coding_questions c where c.category = 'behavioral' and c.title = v.title);

-- Theory gaps, 41: TypeScript (bank had 1), Accessibility, React 19 / RSC / Next.js App Router, auth-token storage and CORS.
insert into coding_questions (title, difficulty, topics, sort_order, answer_hints, category, source, url)
select v.title, v.difficulty, v.topics, v.sort_order::int, v.answer_hints, 'quiz', 'Prep additions', null
from (values
  ('What is the difference between type and interface in TypeScript?', 'easy', array['TypeScript']::text[], null, 'both describe object shapes · interfaces support declaration merging and extends, types support unions/intersections/mapped/conditional types · prefer interface for public object contracts, type for compositions'),
  ('What are generics in TypeScript, and when would you use constraints?', 'medium', array['TypeScript']::text[], null, 'type parameters for reusable type-safe code (e.g. useState<T>), extends constraints (T extends { id: string }), default type params, inference from arguments'),
  ('Explain unknown vs any vs never.', 'medium', array['TypeScript']::text[], null, 'any disables checking · unknown is the safe top type — must narrow before use · never is the empty type — unreachable code, exhaustive switch checks'),
  ('What are discriminated unions, and how do they help in React state?', 'medium', array['TypeScript']::text[], null, 'union of objects sharing a literal tag (status: ''loading'' | ''success'' | ''error''), narrowing by the tag, impossible states become unrepresentable, exhaustive checks with never'),
  ('How do you narrow types in TypeScript?', 'medium', array['TypeScript']::text[], null, 'typeof, instanceof, in, equality, discriminant property, user-defined type guards (x is T), assertion functions'),
  ('Explain mapped and conditional types with an example.', 'hard', array['TypeScript']::text[], null, 'mapped: { [K in keyof T]: ... } (Partial, Readonly), key remapping · conditional: T extends U ? X : Y, distributive over unions, infer keyword (ReturnType)'),
  ('Name the utility types you use most and what they do.', 'easy', array['TypeScript']::text[], null, 'Partial, Required, Pick, Omit, Record, Readonly, ReturnType, Parameters, NonNullable, Awaited — with a real use for each'),
  ('How do you type React components, props, children, and events?', 'medium', array['TypeScript', 'React & State Management']::text[], null, 'props interfaces, React.ReactNode for children, ComponentProps<''button''> to extend native props, event types (React.ChangeEvent<HTMLInputElement>), avoid React.FC debates, generic components'),
  ('What does satisfies do, and how is it different from a type annotation?', 'medium', array['TypeScript']::text[], null, 'checks a value conforms to a type while keeping the narrower inferred type (literal keys preserved), unlike annotation which widens to the declared type'),
  ('What does as const do?', 'easy', array['TypeScript']::text[], null, 'makes literals readonly and narrowest literal types — tuple instead of array, string literal unions from arrays (typeof arr[number])'),
  ('How would you type an API response safely when you can''t trust the server?', 'hard', array['TypeScript']::text[], null, 'types are compile-time only · validate at runtime at the boundary (zod/valibot), infer types from the schema, handle parse failure explicitly'),
  ('What is structural typing, and what pitfalls does it cause?', 'medium', array['TypeScript']::text[], null, 'compatibility by shape not name · excess property checks only on fresh literals · branded types to distinguish UserId vs OrderId'),
  ('How does keyof and indexed access (T[K]) work?', 'medium', array['TypeScript']::text[], null, 'keyof T gives a union of keys · T[K] looks up the property type · together for type-safe getters like get<T, K extends keyof T>(obj: T, key: K): T[K]'),
  ('What''s the difference between strict mode options like strictNullChecks and noImplicitAny, and why enable them?', 'easy', array['TypeScript']::text[], null, 'strictNullChecks makes null/undefined explicit, noImplicitAny forces annotations where inference fails · catches whole classes of runtime errors · enable in new code, migrate incrementally'),
  ('How do function overloads work in TypeScript, and when would you use a union or generic instead?', 'hard', array['TypeScript']::text[], null, 'multiple signatures + one implementation signature · prefer unions/generics when return type follows input simply · overloads for genuinely different call shapes'),
  ('What is semantic HTML, and why does it matter for accessibility?', 'easy', array['Accessibility']::text[], null, 'native elements carry roles, states and keyboard behavior (button, nav, main, label) · screen readers and assistive tech rely on them · less ARIA needed'),
  ('What''s the first rule of ARIA, and when should you use ARIA attributes?', 'medium', array['Accessibility']::text[], null, 'don''t use ARIA if a native element works · ARIA changes semantics only, not behavior · use for custom widgets (combobox, tabs) following APG patterns'),
  ('How do you make a custom component keyboard accessible?', 'medium', array['Accessibility']::text[], null, 'focusable (tabindex=0 or native), Enter/Space activation, arrow keys within composite widgets (roving tabindex), Escape to close, visible focus, logical tab order'),
  ('How do you manage focus when opening and closing a modal dialog?', 'medium', array['Accessibility']::text[], null, 'move focus into the dialog, trap focus, Escape closes, return focus to the trigger, aria-modal/role=dialog with a label, inert background (native <dialog>)'),
  ('What is an aria-live region, and when would you use one?', 'medium', array['Accessibility']::text[], null, 'announces dynamic updates without moving focus · polite vs assertive · for toasts, form status, search result counts · don''t announce every keystroke'),
  ('What are WCAG color contrast requirements?', 'easy', array['Accessibility']::text[], null, 'AA: 4.5:1 normal text, 3:1 large text and UI components/focus indicators · AAA 7:1 · don''t convey info by color alone'),
  ('How do you make forms accessible?', 'easy', array['Accessibility']::text[], null, 'labels tied to inputs, fieldset/legend for groups, errors linked via aria-describedby and announced, aria-invalid, don''t rely on placeholder, clear required indication'),
  ('How would you test a web app for accessibility?', 'medium', array['Accessibility', 'Testing']::text[], null, 'automated (axe, Lighthouse, eslint-plugin-jsx-a11y, jest-axe/Playwright axe) catches ~30–40% · manual keyboard-only pass, screen reader (VoiceOver/NVDA), zoom 200%, reduced motion'),
  ('What is the accessible name of an element, and how is it computed?', 'hard', array['Accessibility']::text[], null, 'the label assistive tech announces · from aria-labelledby > aria-label > native label/alt/content > title · icon buttons need one'),
  ('How do you handle accessibility in a single-page app''s route changes?', 'hard', array['Accessibility']::text[], null, 'move focus to the new page heading or main, update document.title, announce the change (live region), restore scroll sensibly'),
  ('What does prefers-reduced-motion do, and how should apps respect it?', 'easy', array['Accessibility', 'CSS & Layout']::text[], null, 'media query for users who reduce motion · disable or reduce non-essential animation and parallax · keep functional transitions short'),
  ('How do you make an icon-only button accessible?', 'easy', array['Accessibility']::text[], null, 'use a real <button>, give an accessible name (aria-label or visually hidden text), hide the decorative svg (aria-hidden), visible focus, adequate target size (24–44px)'),
  ('What are React Server Components, and how do they differ from SSR?', 'hard', array['React & State Management', 'Next.js']::text[], null, 'RSC run only on the server and ship no JS, can fetch data directly · SSR renders client components to HTML then hydrates · RSC and client components compose, ''use client'' boundary'),
  ('When do you need ''use client'' in Next.js App Router?', 'medium', array['Next.js']::text[], null, 'state, effects, event handlers, browser APIs, context providers · keep the boundary low in the tree · server components can render client components and pass serializable props'),
  ('Explain caching and revalidation in the Next.js App Router.', 'hard', array['Next.js']::text[], null, 'fetch cache / data cache, revalidate by time or on demand (revalidatePath/revalidateTag), static vs dynamic rendering, router cache on the client · know what''s cached where'),
  ('What are Server Actions, and what are their trade-offs?', 'medium', array['Next.js']::text[], null, 'async server functions callable from forms/client, progressive enhancement, no API route boilerplate · must validate input and auth like any endpoint, harder to reuse outside Next'),
  ('How do Suspense and streaming work in Next.js?', 'medium', array['Next.js', 'React & State Management']::text[], null, 'loading.tsx and <Suspense> boundaries stream HTML as data resolves, faster TTFB/FCP, avoid waterfalls by fetching in parallel'),
  ('What is useTransition / concurrent rendering, and when would you use it?', 'hard', array['React & State Management']::text[], null, 'mark updates non-urgent so input stays responsive, isPending for feedback, interruptible rendering · e.g. filtering a large list · useDeferredValue as the value-based counterpart'),
  ('What is the React Compiler, and how does it change memoization?', 'medium', array['React & State Management', 'Performance']::text[], null, 'auto-memoizes components and hooks at build time, reduces manual useMemo/useCallback/memo, relies on following the Rules of React'),
  ('What new hooks did React 19 add, and what problems do they solve?', 'medium', array['React & State Management']::text[], null, 'useActionState, useFormStatus, useOptimistic for forms/mutations, use() for promises/context, ref as a prop · less boilerplate for async UI'),
  ('How would you prevent data-fetching waterfalls in a React or Next.js app?', 'hard', array['React & State Management', 'Performance']::text[], null, 'fetch in parallel (Promise.all), hoist fetches to route/server level, preload, avoid fetch-in-child-after-parent-renders, Suspense boundaries, caching libraries (TanStack Query)'),
  ('Compare client-side state libraries: Context, Redux Toolkit, Zustand, TanStack Query. When do you use each?', 'medium', array['React & State Management']::text[], null, 'server state vs client state · TanStack Query for server cache, Zustand/RTK for complex shared client state, Context for low-frequency values · re-render costs of Context'),
  ('How should a frontend store auth tokens, and what are the trade-offs?', 'hard', array['Networking & APIs']::text[], null, 'HttpOnly secure SameSite cookies resist XSS token theft but need CSRF protection · localStorage is XSS-exposed · short-lived access + refresh rotation · BFF pattern'),
  ('What is CORS, and why doesn''t it protect your API from attackers?', 'medium', array['Networking & APIs']::text[], null, 'browser-enforced read permission for cross-origin responses · preflight for non-simple requests · servers and curl ignore it — authZ must be server-side'),
  ('What is clickjacking, and how do you prevent it?', 'easy', array['Networking & APIs']::text[], null, 'embedding your site in a hidden iframe to trick clicks · X-Frame-Options / CSP frame-ancestors'),
  ('How do you secure third-party scripts and dependencies on the frontend?', 'medium', array['Networking & APIs', 'Performance']::text[], null, 'Subresource Integrity, CSP allowlists, lockfiles and audit, minimal deps, sandboxed iframes for widgets, load async, monitor supply-chain advisories')
) as v(title, difficulty, topics, sort_order, answer_hints)
where not exists (select 1 from coding_questions c where c.category = 'quiz' and c.title = v.title);

-- UI coding, 20 components the GreatFrontEnd set lacks (autocomplete, toasts, menus, virtualization, drag and drop, date picker...).
insert into coding_questions (title, difficulty, topics, sort_order, answer_hints, category, source, url)
select v.title, v.difficulty, v.topics, v.sort_order::int, v.answer_hints, 'ui-coding', 'Prep additions', null
from (values
  ('Autocomplete / Typeahead', 'hard', array['UI Components', 'Async & Promises']::text[], null, 'debounce input, cancel stale requests (AbortController), ignore out-of-order responses, cache results, loading/empty/error states, highlight match, keyboard ↑↓ Enter Esc, ARIA combobox + listbox + aria-activedescendant'),
  ('Toast notifications', 'medium', array['UI Components']::text[], null, 'queue with max visible, auto-dismiss with pause on hover/focus, manual close, variants, portal, aria-live polite (assertive for errors), useToast() API'),
  ('Dropdown menu (accessible)', 'medium', array['UI Components', 'DOM & Browser APIs']::text[], null, 'button aria-haspopup/aria-expanded, menu/menuitem roles, arrow-key navigation, typeahead, Esc closes and returns focus, click outside closes, positioning/flip at viewport edge'),
  ('Tooltip', 'easy', array['UI Components']::text[], null, 'show on hover AND focus, delay, Esc dismisses, aria-describedby, positioning without overflow, don''t put interactive content in a tooltip'),
  ('Infinite scroll list', 'medium', array['UI Components', 'Performance']::text[], null, 'IntersectionObserver sentinel, page/cursor state, prevent duplicate fetches, loading and end-of-list states, error retry, preserve scroll on back'),
  ('Virtualized list (10,000 rows)', 'hard', array['UI Components', 'Performance']::text[], null, 'render only visible rows + overscan, fixed vs variable heights (measure + cache), scroll container with spacer height, smooth scrolling, keep focus/selection stable'),
  ('Drag-and-drop sortable list', 'hard', array['UI Components', 'DOM & Browser APIs']::text[], null, 'pointer events (or HTML5 DnD), placeholder, reorder state immutably, keyboard alternative (space to lift, arrows to move), announce moves via live region, touch support'),
  ('Kanban board', 'hard', array['UI Components', 'React & State Management']::text[], null, 'columns + cards state shape normalized by id, drag between columns, optimistic update with rollback, add/edit card, keyboard moves'),
  ('Date picker', 'hard', array['UI Components']::text[], null, 'calendar grid, month navigation, min/max and disabled dates, keyboard grid navigation, locale/first-day-of-week, input parsing, ARIA grid/dialog'),
  ('Multi-select with chips', 'medium', array['UI Components']::text[], null, 'searchable options, selected chips with remove, Backspace removes last, keyboard navigation, controlled value API, ARIA multiselectable listbox'),
  ('Pagination component', 'easy', array['UI Components']::text[], null, 'page numbers with ellipsis logic, prev/next disabled states, current page aria-current, controlled page prop, page size'),
  ('Multi-step form wizard', 'medium', array['UI Components', 'React & State Management']::text[], null, 'per-step validation, shared form state, back without losing data, progress indicator, focus heading on step change, submit at end, persist draft'),
  ('File uploader with progress', 'medium', array['UI Components', 'Networking & APIs']::text[], null, 'drag-drop + input, file type/size validation, per-file progress (XHR upload events or fetch streams), cancel, retry, previews, accessible status'),
  ('Comment box with @mentions', 'hard', array['UI Components']::text[], null, 'detect @ trigger, filtered suggestions popover, insert mention token, keyboard select, caret positioning, serialize to text/ids'),
  ('useFetch hook with cancellation and caching', 'medium', array['React & State Management', 'Async & Promises']::text[], null, 'status/data/error, AbortController cleanup on unmount and dep change, race-safe, simple cache keyed by URL, refetch, StrictMode double-effect safe'),
  ('useDebounce and useThrottle hooks', 'easy', array['React & State Management', 'Performance']::text[], null, 'timer refs, cleanup on unmount, stable callbacks, leading/trailing options, explain debounce vs throttle use cases'),
  ('Dark mode toggle without flash', 'medium', array['UI Components', 'CSS & Layout']::text[], null, 'CSS variables per theme, respect prefers-color-scheme, persist choice, inline script before paint to set data-theme (no FOUC), SSR-safe'),
  ('Resizable split pane', 'medium', array['UI Components', 'DOM & Browser APIs']::text[], null, 'pointer capture on the divider, min/max sizes, keyboard arrows on the separator (role=separator, aria-valuenow), persist size, cursor styles'),
  ('Tree view with expand/collapse and selection', 'medium', array['UI Components']::text[], null, 'recursive render, expanded set state, keyboard (arrows, Home/End), ARIA tree/treeitem/aria-expanded, lazy-load children'),
  ('Image gallery with lightbox', 'medium', array['UI Components', 'Performance']::text[], null, 'lazy-loaded thumbnails with srcset, open modal on click, arrow navigation and swipe, Esc closes, focus management, preload neighbors')
) as v(title, difficulty, topics, sort_order, answer_hints)
where not exists (select 1 from coding_questions c where c.category = 'ui-coding' and c.title = v.title);

-- Frontend system design, 20 more prompts (20 to 40), incl. a sales-engagement CRM and an AI chat frontend.
insert into coding_questions (title, difficulty, topics, sort_order, answer_hints, category, source, url)
select v.title, v.difficulty, v.topics, v.sort_order::int, v.answer_hints, 'system-design', 'Prep additions', null
from (values
  ('Notification center with real-time updates', 'medium', array['System Design', 'Networking & APIs']::text[], null, 'WebSocket/SSE vs polling, unread counts, pagination, mark-read optimistic, grouping, toast + inbox, reconnect and missed-event sync, a11y announcements'),
  ('Kanban board (e.g. Trello)', 'hard', array['System Design', 'React & State Management']::text[], null, 'normalized board/list/card state, fractional indexing for order, drag-and-drop, optimistic moves with conflict resolution, real-time collaboration, offline queue'),
  ('Calendar app (e.g. Google Calendar)', 'hard', array['System Design']::text[], null, 'day/week/month views, event layout for overlaps, time zones and DST, recurring events (RRULE) expansion, virtualization, drag to create/resize, keyboard a11y'),
  ('File upload and storage UI (e.g. Dropbox / Google Drive)', 'hard', array['System Design', 'Networking & APIs']::text[], null, 'chunked resumable uploads, direct-to-storage presigned URLs, progress and retry, folder tree, large lists, previews, sharing permissions UI'),
  ('Analytics dashboard with charts and filters', 'hard', array['System Design', 'Performance']::text[], null, 'filter state in URL, server-side aggregation, caching and request dedup, chart rendering cost (canvas vs SVG), skeletons, large tables virtualized, export'),
  ('Form builder (e.g. Typeform / Google Forms)', 'hard', array['System Design']::text[], null, 'schema-driven forms (JSON schema), builder vs renderer separation, validation rules, conditional logic, drafts/autosave, versioning, accessible rendering'),
  ('Threaded comments (e.g. Reddit)', 'medium', array['System Design']::text[], null, 'tree data model (adjacency vs flat with parent ids), lazy-load deep threads, sorting, optimistic post, voting, collapse, moderation states'),
  ('In-browser code editor / playground (e.g. CodeSandbox)', 'hard', array['System Design', 'Performance']::text[], null, 'editor (Monaco/CodeMirror), bundling in a web worker, sandboxed iframe preview with postMessage, file tree, autosave, security isolation'),
  ('Real-time stock ticker / trading dashboard', 'hard', array['System Design', 'Performance']::text[], null, 'WebSocket stream, throttle/batch updates per frame, avoid re-rendering whole tables, canvas charts, stale/reconnect indicators, number formatting'),
  ('Feature-flag and A/B testing client SDK', 'hard', array['System Design']::text[], null, 'bootstrapping flags without flicker (SSR/edge), caching, sticky bucketing, exposure events, typed flags, kill switch, minimal bundle size'),
  ('Frontend error-tracking and analytics SDK (e.g. Sentry-like)', 'hard', array['System Design', 'Networking & APIs']::text[], null, 'global error/unhandledrejection hooks, breadcrumbs, batching with sendBeacon, sampling, source maps, PII scrubbing, tiny footprint and no impact on app perf'),
  ('Component library / design system for many product teams', 'hard', array['System Design', 'UI Components']::text[], null, 'tokens (color/spacing/type) and theming, headless vs styled components, a11y baked in, versioning and breaking changes, docs (Storybook), visual regression tests, adoption'),
  ('Micro-frontend shell for a large organization', 'hard', array['System Design']::text[], null, 'composition (module federation vs build-time vs iframes), shared deps and versions, routing ownership, design-system consistency, independent deploys, performance budget'),
  ('Offline-first notes app (PWA)', 'hard', array['System Design', 'Networking & APIs']::text[], null, 'service worker caching strategies, IndexedDB local store, sync queue, conflict resolution (last-write-wins vs CRDT), install prompt, storage limits'),
  ('Internationalization for a large app (20+ locales, RTL)', 'medium', array['System Design']::text[], null, 'message catalogs and ICU plurals, lazy-loaded locale bundles, Intl formatting (dates, numbers, currency), RTL logical CSS properties, translation workflow, pseudo-localization testing'),
  ('E-commerce search results page with faceted filters', 'medium', array['System Design', 'Performance']::text[], null, 'filters in URL, debounced queries, facet counts, pagination vs infinite scroll, SEO/SSR, skeletons, image optimization, analytics events'),
  ('Checkout flow (multi-step, payments)', 'hard', array['System Design']::text[], null, 'step state and validation, address autocomplete, payment provider iframes/PCI scope, idempotent submit and double-click guard, error recovery, analytics funnel, a11y'),
  ('Maps and location search (e.g. Google Maps)', 'hard', array['System Design', 'Performance']::text[], null, 'tiled map rendering, marker clustering, viewport-based fetching, debounced pan/zoom queries, list ↔ map sync, geolocation permission UX'),
  ('Sales-engagement CRM (e.g. Apollo: contacts, sequences, inbox)', 'hard', array['System Design', 'React & State Management']::text[], null, 'huge contact tables (virtualized, server-side filter/sort), saved views in URL, bulk actions with progress, email sequence builder, real-time inbox, permissions, AI-assisted drafting UI'),
  ('AI chat assistant frontend (e.g. ChatGPT-like)', 'hard', array['System Design', 'Networking & APIs']::text[], null, 'streaming via SSE/fetch streams, conversation/branch data model, stop/regenerate/edit, safe markdown + code rendering, long-history virtualization, BFF for keys and rate limits, feedback + evals hooks')
) as v(title, difficulty, topics, sort_order, answer_hints)
where not exists (select 1 from coding_questions c where c.category = 'system-design' and c.title = v.title);
