-- v3.5 (2026-10-09): prep realigned to the current market.
-- 1) A new 'angular' Question Bank category (Track A: senior / lead Angular
--    roles at banks, fintech and GCCs). Prep-only rows (url null) answered in
--    the app with answer_hints as the key points and AI rating.
-- 2) A 'machine-coding' Mock Round format (90-minute build of one component).
-- Safe to re-run. No backticks and no semicolons inside text values (the
-- Supabase SQL Editor splits statements on them).

insert into coding_questions (title, difficulty, topics, sort_order, answer_hints, category, source, url)
select v.title, v.difficulty, v.topics, v.sort_order::int, v.answer_hints, 'angular', 'Prep additions', null
from (values
  ('What are Angular Signals and why were they introduced?', 'medium', array['Signals', 'Must-have']::text[], 1, 'reactive primitive holding a value (signal, set, update), fine-grained change tracking instead of zone-wide checks, computed for derived state, effect for side effects, path to zoneless and better performance'),
  ('Signals vs RxJS Observables — when do you use which?', 'hard', array['Signals', 'RxJS', 'Must-have']::text[], 2, 'signals for synchronous UI state and derived values, observables for async streams, events, cancellation and time-based operators (debounce, switchMap) · interop via toSignal and toObservable · avoid forcing one model everywhere'),
  ('Explain computed() and effect(). What are the pitfalls of effects?', 'medium', array['Signals']::text[], 3, 'computed is lazy, memoized and read-only, effect runs side effects when dependencies change · pitfalls: writing signals inside effects (loops), using effects for derived state instead of computed, cleanup with onCleanup, untracked reads'),
  ('How does Angular change detection work, and what does OnPush change?', 'hard', array['Change detection', 'Must-have']::text[], 4, 'Zone.js patches async APIs and triggers a tree check from the root · Default checks every component, OnPush only on input reference change, events in the component, async pipe emissions or markForCheck / signals · immutability matters'),
  ('What is zoneless Angular and how do you migrate toward it?', 'hard', array['Change detection', 'Performance']::text[], 5, 'provideZonelessChangeDetection, no Zone.js patching, change detection scheduled by signals, markForCheck, async pipe and events · migrate: OnPush everywhere, signals for state, remove reliance on setTimeout-triggered CD, test third-party libs'),
  ('How do you debug a slow Angular screen?', 'hard', array['Performance', 'Must-have']::text[], 6, 'Angular DevTools profiler (change detection cycles, slow components), Chrome Performance panel, too many bindings or function calls in templates, missing trackBy / track in loops, Default CD in large trees, heavy pipes, unsubscribed streams'),
  ('Explain the new control flow (@if, @for, @switch) and why @for requires track.', 'medium', array['Templates']::text[], 7, 'built-in syntax replacing structural directives, better type narrowing and performance, @empty block · track gives identity so the DOM is reused instead of re-created on list changes'),
  ('What are @defer blocks and when would you use them?', 'medium', array['Performance']::text[], 8, 'lazy-load parts of a template with triggers (on viewport, interaction, idle, timer, when condition), placeholder, loading and error blocks, smaller initial bundles, good for below-the-fold or heavy widgets'),
  ('Standalone components vs NgModules — what changed and how do you migrate?', 'medium', array['Architecture', 'Must-have']::text[], 9, 'standalone: true (default since v19), imports declared on the component, bootstrapApplication with providers, lazy loadComponent routes · migrate with the schematic, move providers to provide functions, keep shared UI as standalone libs'),
  ('Explain Angular dependency injection: hierarchical injectors and provider scopes.', 'hard', array['Components & DI', 'Must-have']::text[], 10, 'environment vs element injectors, providedIn root vs component providers, resolution walks up the tree, inject() function, InjectionToken, useClass / useValue / useFactory, multi providers, why component-level providers give per-instance services'),
  ('What is the inject() function and why is it preferred now?', 'medium', array['Components & DI']::text[], 11, 'injection outside constructors (field initializers, functions, guards), enables functional guards / resolvers / interceptors, better with inheritance, must run in an injection context'),
  ('How do you avoid memory leaks with RxJS in Angular?', 'medium', array['RxJS', 'Must-have']::text[], 12, 'async pipe, takeUntilDestroyed with DestroyRef, toSignal, avoid nested subscribes, complete subjects, unsubscribe long-lived streams (intervals, store selects, websockets)'),
  ('switchMap vs mergeMap vs concatMap vs exhaustMap — give a use case for each.', 'hard', array['RxJS', 'Must-have']::text[], 13, 'switchMap cancels previous (typeahead search), mergeMap parallel (independent saves), concatMap queued in order (sequential writes), exhaustMap ignores while busy (login / submit button double-click)'),
  ('Subject vs BehaviorSubject vs ReplaySubject — when would you use each?', 'medium', array['RxJS']::text[], 14, 'Subject has no initial value (events), BehaviorSubject holds the current value (state), ReplaySubject replays N past values (late subscribers), expose as asObservable, consider signals for simple state'),
  ('How do you implement a typeahead search with RxJS?', 'medium', array['RxJS']::text[], 15, 'valueChanges or input events, debounceTime, distinctUntilChanged, filter min length, switchMap to the API with catchError, loading state, cancel stale requests, a11y combobox semantics'),
  ('Hot vs cold observables — and what does shareReplay do?', 'hard', array['RxJS']::text[], 16, 'cold: each subscriber gets its own execution (HTTP), hot: shared source (events, subjects) · shareReplay multicasts and caches the last values, refCount to avoid leaks, use for shared HTTP data'),
  ('How would you structure state management in a large Angular app?', 'hard', array['State (NgRx)', 'Architecture', 'Must-have']::text[], 17, 'local signals in components, services with signals for feature state, NgRx Store or SignalStore for shared complex state, server state separate (cache, refetch), avoid global store for everything, clear ownership per feature'),
  ('NgRx Store vs NgRx SignalStore vs a signal-based service — trade-offs?', 'hard', array['State (NgRx)']::text[], 18, 'Store: actions / reducers / effects, devtools, strong for complex event flows but boilerplate · SignalStore: lighter, signals-first, withState / withComputed / withMethods · service with signals: simplest for feature state'),
  ('Explain NgRx effects and how you handle errors and side effects.', 'medium', array['State (NgRx)']::text[], 19, 'effects listen to actions, call services, map to success or failure actions, catchError inside the inner observable so the effect stream survives, flattening operator choice matters, non-dispatching effects for navigation or logging'),
  ('Reactive forms vs template-driven forms — and how do you build a typed dynamic form?', 'medium', array['Routing & forms']::text[], 20, 'reactive: explicit FormGroup / FormControl, typed forms (v14+), testable, dynamic FormArray · template-driven for simple forms · custom validators, async validators, cross-field validation, ControlValueAccessor for custom inputs'),
  ('How does ControlValueAccessor work? Build a custom form control.', 'hard', array['Routing & forms']::text[], 21, 'implement writeValue, registerOnChange, registerOnTouched, setDisabledState, provide NG_VALUE_ACCESSOR, works with both form types, keyboard and a11y behaviour'),
  ('Explain routing in modern Angular: lazy loading, functional guards and resolvers.', 'medium', array['Routing & forms']::text[], 22, 'loadComponent / loadChildren, CanActivateFn / CanMatchFn with inject(), ResolveFn, route input binding (withComponentInputBinding), preloading strategies, guards for auth and unsaved changes'),
  ('How do HTTP interceptors work and what would you use them for?', 'medium', array['Components & DI']::text[], 23, 'functional interceptors with withInterceptors, auth tokens, retry and error handling, logging, caching, loading indicators, order of interceptors, avoid leaking tokens to third-party domains'),
  ('Explain Angular SSR and hydration. What changed with incremental hydration?', 'hard', array['Performance', 'SSR']::text[], 24, 'server renders HTML for fast first paint and SEO, hydration reuses the DOM instead of re-rendering, event replay, incremental hydration hydrates @defer blocks on triggers · watch browser-only APIs (window, localStorage) via isPlatformBrowser / afterNextRender'),
  ('How do you reduce bundle size in an Angular app?', 'medium', array['Performance']::text[], 25, 'lazy routes and @defer, standalone tree-shaking, analyze with source-map-explorer / esbuild metafile, remove heavy deps (moment, lodash full), budgets in angular.json, modern esbuild builder, image optimization with NgOptimizedImage'),
  ('What is NgOptimizedImage and which Core Web Vitals does it help?', 'easy', array['Performance']::text[], 26, 'enforces width / height to prevent CLS, priority for the LCP image (preload, fetchpriority), lazy loading by default, srcset generation with loaders, warns about common mistakes'),
  ('Content projection: ng-content, ng-template and ngTemplateOutlet — when do you use each?', 'medium', array['Templates', 'Components & DI']::text[], 27, 'ng-content with select for slots (static projection, always instantiated), ng-template + ngTemplateOutlet for lazy / repeated / context-based rendering, used in reusable design-system components'),
  ('Component communication in Angular — what are the options today?', 'easy', array['Components & DI']::text[], 28, 'input() and output() signal APIs, model() for two-way binding, services with signals for siblings, ViewChild / viewChild(), avoid deep prop chains, router state for page-level data'),
  ('How do you architect a large Angular codebase for multiple teams?', 'hard', array['Architecture', 'Must-have']::text[], 29, 'feature / domain libraries (Nx), clear public APIs per lib, module boundary lint rules, shared UI and data-access libs, standalone components, consistent state approach, CI affected builds, ownership and code owners'),
  ('Micro-frontends with Angular: Module Federation or Native Federation — when is it worth it?', 'hard', array['Architecture']::text[], 30, 'independent deploys for separate teams, shared dependencies (singletons, version skew), routing and auth across remotes, design-system consistency, performance cost · often a well-structured monorepo is enough'),
  ('How would you migrate a large AngularJS or legacy Angular app incrementally?', 'hard', array['Migration']::text[], 31, 'strangler pattern, upgrade path one major at a time with ng update, hybrid or route-by-route rewrite, standalone and signals adoption gradually, test coverage first, feature flags, measure regressions'),
  ('How do you migrate an Angular app to React (or vice versa) without a big-bang rewrite?', 'hard', array['Migration', 'Architecture']::text[], 32, 'route-level or widget-level strangler, web components or micro-frontend boundary, shared design tokens, shared API layer, team upskilling, measure parity, decide by business value not taste'),
  ('How do you test Angular components and services?', 'medium', array['Testing']::text[], 33, 'TestBed with standalone imports, component harnesses, HttpTestingController, mocking with providers, testing signals and OnPush (fixture.detectChanges, whenStable), Jest or Vitest runners, Playwright / Cypress for E2E'),
  ('What security protections does Angular give you, and where can you still get XSS?', 'medium', array['Security']::text[], 34, 'automatic sanitization and escaping in templates, DomSanitizer bypass is the risk, innerHTML with untrusted data, URL and resource URL contexts, CSP and trusted types support, HttpClient XSRF support'),
  ('Pure vs impure pipes — and why are function calls in templates a problem?', 'easy', array['Templates', 'Performance']::text[], 35, 'pure pipes recompute only on input reference change (memoized), impure every CD cycle · template function calls run on every check, use pipes, computed signals or precomputed values instead'),
  ('ViewChild vs ContentChild and the lifecycle hooks around them.', 'medium', array['Components & DI']::text[], 36, 'ViewChild queries the component template (available in ngAfterViewInit), ContentChild queries projected content (ngAfterContentInit), signal queries viewChild() / contentChild(), static option, avoid DOM manipulation outside renderer'),
  ('What is new in recent Angular versions that you would adopt in a new project?', 'medium', array['Signals', 'Architecture']::text[], 37, 'standalone by default, signals + signal inputs / outputs / model, new control flow, @defer, esbuild / Vite builder, SSR with incremental hydration, zoneless, resource() for async data, inject()'),
  ('How do you handle async data with signals — resource() and httpResource?', 'hard', array['Signals']::text[], 38, 'resource() derives async data from signal params with loading / error / value states, reloads when params change, cancellation via abort signal, httpResource for HTTP · compare with toSignal(observable)'),
  ('Design a reusable data-grid component library in Angular for multiple teams.', 'hard', array['Architecture', 'Components & DI']::text[], 39, 'API design (inputs, outputs, templates for cells), virtual scrolling (CDK), sorting / filtering server vs client, OnPush + signals, accessibility (grid role, keyboard), theming via CSS variables, versioning and docs'),
  ('Tell me about the most complex Angular application you have worked on.', 'medium', array['Experience', 'Must-have']::text[], 40, 'scale (users, modules, team size), architecture choices, a hard problem (performance, state, migration) and how you solved it, measurable outcome, what you would do differently today with signals / standalone')
) as v(title, difficulty, topics, sort_order, answer_hints)
where not exists (select 1 from coding_questions c where c.category = 'angular' and c.title = v.title);

-- Machine-coding Mock Round format.
alter table mock_rounds drop constraint if exists mock_rounds_format_check;
alter table mock_rounds add constraint mock_rounds_format_check
  check (format in ('screen', 'behavioral', 'system-design', 'machine-coding'));
